/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/Button.vue')['default']
    CheckBox: typeof import('./components/CheckBox.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    Loading: typeof import('./components/Loading.vue')['default']
    LoadingOverlay: typeof import('./components/LoadingOverlay.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    PageTopButton: typeof import('./components/PageTopButton.vue')['default']
    Radio: typeof import('./components/Radio.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
